In [5]:
# import the required python libraries like pandas and numpy

import pandas as pd
import numpy as np

# store the movie credits and movie information csv files into a dataframe into their respective variables
credits = pd.read_csv("tmdb_5000_credits.csv")
movies = pd.read_csv("tmdb_5000_movies.csv")

# as we are using the overview column for recommendation
# we cannot have empty cell in the 'overview' column
# so we store only non empty cells
movies = movies[movies['overview'].notna()]

In [6]:
# to view the first 5 rows of the 'credits' dataframe
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
# to view the first 5 rows of the 'movies' dataframe
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [8]:
# To know the size(rows and columns) of each dataframe 
print("Credits:",credits.shape)
print("Movies Dataframe:",movies.shape)

Credits: (4803, 4)
Movies Dataframe: (4800, 20)

In [9]:
# renaming the column name 'movie_id' to 'id' as it is mapped to 'id' in the 'movies' dataframe
credits_column_renamed = credits.rename(index=str, columns={"movie_id": "id"})

# merge both the dataframe with same id
movies_merge = movies.merge(credits_column_renamed, on='id')
print(movies_merge.head())

      budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995
1  http://disney.go.com/disneypictures/pirates/     285
2   http://www.sonypictures.com/movies/spectre/  206647
3            http://www.thedarkknightrises.com/   49026
4          http://movies.disney.com/john-carter   49529

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4  [{"id": 818, "name": "based on novel"}, {"id":...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577
1  Captain Barbossa, long believed to be dead, ha...  139.082615
2  A cryptic message from Bondâ€™s past sends him o...  107.376788
3  Following the death of District Attorney Harve...  112.312950
4  John Carter is a war-weary, former military ca...   43.926995

                                production_companies  ... runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   148.0
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...   165.0
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...   132.0

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1           [{"iso_639_1": "en", "name": "English"}]  Released
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3           [{"iso_639_1": "en", "name": "English"}]  Released
4           [{"iso_639_1": "en", "name": "English"}]  Released

                                          tagline  \
0                     Enter the World of Pandora.
1  At the end of the world, the adventure begins.
2                           A Plan No One Escapes
3                                 The Legend Ends
4            Lost in our world, found in another.

                                    title_x vote_average vote_count  \
0                                    Avatar          7.2      11800
1  Pirates of the Caribbean: At World's End          6.9       4500
2                                   Spectre          6.3       4466
3                     The Dark Knight Rises          7.6       9106
4                               John Carter          6.1       2124

                                    title_y  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...
1  [{"cast_id": 4, "character": "Captain Jack Spa...
2  [{"cast_id": 1, "character": "James Bond", "cr...
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4  [{"cast_id": 5, "character": "John Carter", "c...

                                                crew
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 23 columns]

In [10]:
# as  columns'homepage', 'title_x', 'title_y', 'status','production_countries'
# are not useful to us in recommendation it is dropped
movies_cleaned = movies_merge.drop(columns=['homepage', 'title_x', 'title_y', 'status','production_countries'])

# let us take a look at our cleaned dataframe
print(movies_cleaned.head())
print(movies_cleaned.info())
print(movies_cleaned.head(1)['overview'])

      budget                                             genres      id  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   19995
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...     285
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...  206647
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   49026
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   49529

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4  [{"id": 818, "name": "based on novel"}, {"id":...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577
1  Captain Barbossa, long believed to be dead, ha...  139.082615
2  A cryptic message from Bondâ€™s past sends him o...  107.376788
3  Following the death of District Attorney Harve...  112.312950
4  John Carter is a war-weary, former military ca...   43.926995

                                production_companies release_date     revenue  \
0  [{"name": "Ingenious Film Partners", "id": 289...   2009-12-10  2787965087
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   2007-05-19   961000000
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   2015-10-26   880674609
3  [{"name": "Legendary Pictures", "id": 923}, {"...   2012-07-16  1084939099
4        [{"name": "Walt Disney Pictures", "id": 2}]   2012-03-07   284139100

   runtime                                   spoken_languages  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...
1    169.0           [{"iso_639_1": "en", "name": "English"}]
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...
3    165.0           [{"iso_639_1": "en", "name": "English"}]
4    132.0           [{"iso_639_1": "en", "name": "English"}]

                                          tagline  vote_average  vote_count  \
0                     Enter the World of Pandora.           7.2       11800
1  At the end of the world, the adventure begins.           6.9        4500
2                           A Plan No One Escapes           6.3        4466
3                                 The Legend Ends           7.6        9106
4            Lost in our world, found in another.           6.1        2124

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...
1  [{"cast_id": 4, "character": "Captain Jack Spa...
2  [{"cast_id": 1, "character": "James Bond", "cr...
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4  [{"cast_id": 5, "character": "John Carter", "c...

                                                crew
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
<class 'pandas.core.frame.DataFrame'>
Int64Index: 4800 entries, 0 to 4799
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4800 non-null   int64
 1   genres                4800 non-null   object
 2   id                    4800 non-null   int64
 3   keywords              4800 non-null   object
 4   original_language     4800 non-null   object
 5   original_title        4800 non-null   object
 6   overview              4800 non-null   object
 7   popularity            4800 non-null   float64
 8   production_companies  4800 non-null   object
 9   release_date          4799 non-null   object
 10  revenue               4800 non-null   int64
 11  runtime               4800 non-null   float64
 12  spoken_languages      4800 non-null   object
 13  tagline               3959 non-null   object
 14  vote_average          4800 non-null   float64
 15  vote_count            4800 non-null   int64
 16  cast                  4800 non-null   object
 17  crew                  4800 non-null   object
dtypes: float64(3), int64(4), object(11)
memory usage: 712.5+ KB
None
0    In the 22nd century, a paraplegic Marine is di...
Name: overview, dtype: object

In [11]:
# using scikit-learn machine learning library 
# It features various classification, regression and clustering algorithms
# Term frequency-inverse document frequency(TF-IDF) is a text vectorizer that transforms
# the text into a usable vector which the machine/algorithm can understand
from sklearn.feature_extraction.text import TfidfVectorizer
tfv = TfidfVectorizer(min_df=3,  
                      max_features=None,
                      strip_accents='unicode', analyzer='word',token_pattern=r'\w{1,}',
                      ngram_range=(1, 3),
                      stop_words = 'english')

In [12]:
# Fitting the TF-IDF on the 'overview' text
tfv_matrix = tfv.fit_transform(movies_cleaned['overview'])
print(tfv_matrix)
print(tfv_matrix.shape)

  (0, 148)	0.30913566371756246
  (0, 1670)	0.2781535990843119
  (0, 431)	0.21084290341291434
  (0, 7055)	0.26867724841908824
  (0, 6447)	0.25667741877727707
  (0, 3582)	0.2178785202491359
  (0, 9393)	0.2414403528962384
  (0, 5907)	0.17991944361394235
  (0, 9717)	0.24435239113511664
  (0, 6543)	0.2959141439419381
  (0, 5972)	0.2747345275641027
  (0, 2634)	0.28189876819471266
  (0, 5658)	0.26104797828891285
  (0, 1514)	0.20118293309533966
  (0, 147)	0.30913566371756246
  (1, 1810)	0.3679407814456213
  (1, 7159)	0.3031047511907221
  (1, 2916)	0.30082286889432774
  (1, 9609)	0.33552276631817174
  (1, 2848)	0.2155618555572584
  (1, 2872)	0.3232521707896168
  (1, 4205)	0.3080323897734429
  (1, 5263)	0.13328606710757795
  (1, 1806)	0.21045468005671297
  (1, 2318)	0.2189172684598073
  :	:
  (4799, 671)	0.15980598144549593
  (4799, 2360)	0.15010628727202774
  (4799, 677)	0.13488940795750576
  (4799, 3736)	0.1485916649401138
  (4799, 3480)	0.14340214731962103
  (4799, 1252)	0.1517332030269128
  (4799, 8137)	0.12006809459398544
  (4799, 2754)	0.11415534350193002
  (4799, 6989)	0.12818526800509908
  (4799, 3238)	0.16239170968496358
  (4799, 5303)	0.14458910213097395
  (4799, 1224)	0.2891782042619479
  (4799, 8494)	0.09379714267041103
  (4799, 10327)	0.09391809788727037
  (4799, 120)	0.13337478562559182
  (4799, 9583)	0.10877409264240305
  (4799, 9065)	0.08441857408988883
  (4799, 2837)	0.14227608940258665
  (4799, 6366)	0.07950410161557432
  (4799, 10321)	0.0834940873310875
  (4799, 10343)	0.1235188394307617
  (4799, 6189)	0.06605491160042325
  (4799, 5155)	0.10830196011623973
  (4799, 10338)	0.08046853120131203
  (4799, 7725)	0.1662596638309422
(4800, 10417)

In [13]:
from sklearn.metrics.pairwise import sigmoid_kernel

# Compute the sigmoid kernel between 2 vectors
sig = sigmoid_kernel(tfv_matrix, tfv_matrix)
print(sig[0])

[0.76163447 0.76159416 0.76159416 ... 0.76159416 0.76159416 0.76159416]

In [14]:
# Reverse mapping of indices and movie titles
indices = pd.Series(movies_cleaned.index, index=movies_cleaned['original_title']).drop_duplicates()
print(indices)

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4795
Newlyweds                                   4796
Signed, Sealed, Delivered                   4797
Shanghai Calling                            4798
My Date with Drew                           4799
Length: 4800, dtype: int64

In [15]:
def give_recomendations(title, sig=sig):
    # Get the index corresponding to 'original_title' of the movie
    idx = indices[title]

    # Get the pairwsie similarity scores with entered movie
    sig_scores = list(enumerate(sig[idx]))

    # Sort the movies from highest to lowest similarity
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)

    # Scores of the 10 most similar movies is at the top
    sig_scores = sig_scores[1:11]

    # Getting their Movie indices
    movie_indices = [i[0] for i in sig_scores]

    # Display the Top 10 most similar movies with thier indices
    return movies_cleaned['original_title'].iloc[movie_indices]

In [ ]:
mov = input('Enter the name of a movie (present in the used dataset) : ')
print('The recommended movies are : \n')
print(give_recomendations(mov))